### ISSUE TITLE
请问一下老大，H7+RTT+LWIP试过了吗

### ISSUE THREAD

**Issue by whj4674672** [liu2guang/bsp_stm32h750#1]
RT。

**Comment by liu2guang** [comment]
不好意思，最近有点忙没咋关注github，我这边暂时还没有，我的板子上用的是RW007 WIFI，没有吧eth印出来，不过有同学跑到了95M的速度。

**Comment by whj4674672** [comment]
谢谢您的回复。这两天RTT公众号推的就是我写的笔记，只能说LWIP跑起来了，但是速度还没有测试，95M是九爷测试的吧




在 2019-05-07 12:00:01，"流光" <notifications@github.com> 写道：


不好意思，最近有点忙没咋关注github，我这边暂时还没有，我的板子上用的是RW007 WIFI，没有吧eth印出来，不过有同学跑到了95M的速度。

**Comment by liu2guang** [comment]
直接加群 214255611，大佬在里面
